# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gogol\Desktop\кладовка\pysimplegui_designer\CURRRRNET\GITA\PySimpleGUI_designer\untitled.ui'
#
# Created by: PySide2 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 863)
        MainWindow.setStyleSheet("/*\n"
"border: 1px solid black;\n"
"*/")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_input_data = QtWidgets.QGroupBox(self.centralwidget)
        self.main_input_data.setMinimumSize(QtCore.QSize(0, 230))
        self.main_input_data.setMaximumSize(QtCore.QSize(16777215, 250))
        self.main_input_data.setAlignment(QtCore.Qt.AlignCenter)
        self.main_input_data.setObjectName("main_input_data")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.main_input_data)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.psg_ui_output = QtWidgets.QPlainTextEdit(self.main_input_data)
        self.psg_ui_output.setMinimumSize(QtCore.QSize(150, 0))
        self.psg_ui_output.setTabStopWidth(8)
        self.psg_ui_output.setObjectName("psg_ui_output")
        self.gridLayout_9.addWidget(self.psg_ui_output, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.main_input_data)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.input__file = QtWidgets.QLineEdit(self.groupBox)
        self.input__file.setObjectName("input__file")
        self.gridLayout_5.addWidget(self.input__file, 1, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.target_object_name = QtWidgets.QLineEdit(self.groupBox)
        self.target_object_name.setObjectName("target_object_name")
        self.gridLayout_5.addWidget(self.target_object_name, 3, 1, 1, 1)
        self.file__browse = QtWidgets.QPushButton(self.groupBox)
        self.file__browse.setObjectName("file__browse")
        self.gridLayout_5.addWidget(self.file__browse, 1, 4, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_12.setHorizontalSpacing(5)
        self.gridLayout_12.setVerticalSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.guitype_qt = QtWidgets.QRadioButton(self.groupBox_4)
        self.guitype_qt.setChecked(False)
        self.guitype_qt.setObjectName("guitype_qt")
        self.gridLayout_12.addWidget(self.guitype_qt, 0, 2, 1, 1)
        self.guitype_wx = QtWidgets.QRadioButton(self.groupBox_4)
        self.guitype_wx.setObjectName("guitype_wx")
        self.gridLayout_12.addWidget(self.guitype_wx, 0, 3, 1, 1)
        self.guitype_tk = QtWidgets.QRadioButton(self.groupBox_4)
        self.guitype_tk.setChecked(True)
        self.guitype_tk.setObjectName("guitype_tk")
        self.gridLayout_12.addWidget(self.guitype_tk, 0, 0, 1, 1)
        self.guitype_web = QtWidgets.QRadioButton(self.groupBox_4)
        self.guitype_web.setChecked(False)
        self.guitype_web.setObjectName("guitype_web")
        self.gridLayout_12.addWidget(self.guitype_web, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 1, 3, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.compile_ = QtWidgets.QPushButton(self.groupBox)
        self.compile_.setObjectName("compile_")
        self.gridLayout_11.addWidget(self.compile_, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 15))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_13.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_13.setHorizontalSpacing(5)
        self.gridLayout_13.setVerticalSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.mouse_clicks_ = QtWidgets.QRadioButton(self.groupBox_5)
        self.mouse_clicks_.setChecked(False)
        self.mouse_clicks_.setObjectName("mouse_clicks_")
        self.gridLayout_13.addWidget(self.mouse_clicks_, 0, 2, 1, 1)
        self.keys_ = QtWidgets.QRadioButton(self.groupBox_5)
        self.keys_.setChecked(True)
        self.keys_.setObjectName("keys_")
        self.gridLayout_13.addWidget(self.keys_, 0, 1, 1, 1)
        self.compile_pp = QtWidgets.QPushButton(self.groupBox_5)
        self.compile_pp.setObjectName("compile_pp")
        self.gridLayout_13.addWidget(self.compile_pp, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_5, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_11, 3, 3, 1, 2)
        self.gridLayout_9.addWidget(self.groupBox, 0, 1, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.clear_psg_output = QtWidgets.QPushButton(self.main_input_data)
        self.clear_psg_output.setObjectName("clear_psg_output")
        self.horizontalLayout_22.addWidget(self.clear_psg_output)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem)
        self.expand_psg_output = QtWidgets.QPushButton(self.main_input_data)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.expand_psg_output.setFont(font)
        self.expand_psg_output.setChecked(False)
        self.expand_psg_output.setObjectName("expand_psg_output")
        self.horizontalLayout_22.addWidget(self.expand_psg_output)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.pass_bad_widgets = QtWidgets.QCheckBox(self.main_input_data)
        self.pass_bad_widgets.setChecked(True)
        self.pass_bad_widgets.setObjectName("pass_bad_widgets")
        self.horizontalLayout_22.addWidget(self.pass_bad_widgets)
        self.try_run_ = QtWidgets.QPushButton(self.main_input_data)
        self.try_run_.setObjectName("try_run_")
        self.horizontalLayout_22.addWidget(self.try_run_)
        self.gridLayout_9.addLayout(self.horizontalLayout_22, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.main_input_data, 0, 0, 1, 1)
        self.examples_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.examples_tabs.setStyleSheet("")
        self.examples_tabs.setObjectName("examples_tabs")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("/*\n"
"border: 1px solid black\n"
"*/")
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout_17.addWidget(self.label_27, 0, 0, 1, 1)
        self.v1 = QtWidgets.QVBoxLayout()
        self.v1.setObjectName("v1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.spinBox_5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_9.addWidget(self.spinBox_5)
        self.v1.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.tab_3)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.spinBox_7 = QtWidgets.QSpinBox(self.frame_7)
        self.spinBox_7.setObjectName("spinBox_7")
        self.horizontalLayout_13.addWidget(self.spinBox_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBox_18 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_18.setObjectName("checkBox_18")
        self.horizontalLayout_14.addWidget(self.checkBox_18)
        self.checkBox_19 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_19.setObjectName("checkBox_19")
        self.horizontalLayout_14.addWidget(self.checkBox_19)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.v1.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_11.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_11.addWidget(self.checkBox_11)
        self.v1.addLayout(self.horizontalLayout_11)
        self.gridLayout_17.addLayout(self.v1, 0, 1, 1, 2)
        self.v2 = QtWidgets.QVBoxLayout()
        self.v2.setContentsMargins(5, 5, 5, 5)
        self.v2.setObjectName("v2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_15.addWidget(self.label_24)
        self.spinBox_8 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_15.addWidget(self.spinBox_8)
        self.v2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_8 = QtWidgets.QFrame(self.tab_3)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_27 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_6.addWidget(self.checkBox_27, 1, 1, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_6.addWidget(self.checkBox_26, 1, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_6.addWidget(self.lineEdit_18, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_8)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_6.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        self.horizontalLayout_7.addWidget(self.frame_8)
        self.v2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.checkBox_24 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_24.setObjectName("checkBox_24")
        self.horizontalLayout_18.addWidget(self.checkBox_24)
        self.checkBox_25 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_25.setObjectName("checkBox_25")
        self.horizontalLayout_18.addWidget(self.checkBox_25)
        self.v2.addLayout(self.horizontalLayout_18)
        self.gridLayout_17.addLayout(self.v2, 0, 3, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem2, 0, 5, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.gridLayout_17.addWidget(self.label_38, 1, 0, 1, 2)
        self.g2 = QtWidgets.QGridLayout()
        self.g2.setObjectName("g2")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.g2.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.g2.addWidget(self.lineEdit_20, 0, 1, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_30.setObjectName("checkBox_30")
        self.g2.addWidget(self.checkBox_30, 2, 0, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_31.setObjectName("checkBox_31")
        self.g2.addWidget(self.checkBox_31, 2, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setObjectName("label_34")
        self.g2.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.checkBox_32 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_10.addWidget(self.checkBox_32, 1, 1, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout_10.addWidget(self.checkBox_33, 1, 0, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_10.addWidget(self.lineEdit_21, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_10.addWidget(self.label_35, 0, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_10.addWidget(self.pushButton_12, 2, 1, 1, 1)
        self.g2.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.g2, 2, 0, 1, 2)
        self.g3 = QtWidgets.QGridLayout()
        self.g3.setObjectName("g3")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.g3.addWidget(self.pushButton_5, 4, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.g3.addWidget(self.lineEdit_14, 0, 1, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_14.setObjectName("checkBox_14")
        self.g3.addWidget(self.checkBox_14, 3, 0, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_15.setObjectName("checkBox_15")
        self.g3.addWidget(self.checkBox_15, 3, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setObjectName("label_28")
        self.g3.addWidget(self.label_28, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_4.addWidget(self.checkBox_17, 1, 1, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_4.addWidget(self.checkBox_16, 1, 0, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_4.addWidget(self.lineEdit_16, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.g3.addLayout(self.gridLayout_4, 2, 0, 1, 2)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.tab_3)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.g3.addWidget(self.horizontalSlider_2, 1, 1, 1, 1)
        self.gridLayout_17.addLayout(self.g3, 2, 2, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(189, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem3, 2, 4, 1, 1)
        self.g5 = QtWidgets.QGridLayout()
        self.g5.setObjectName("g5")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.g5.addWidget(self.lineEdit_22, 0, 1, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_34.setObjectName("checkBox_34")
        self.g5.addWidget(self.checkBox_34, 2, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_3)
        self.label_36.setObjectName("label_36")
        self.g5.addWidget(self.label_36, 0, 0, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_35.setObjectName("checkBox_35")
        self.g5.addWidget(self.checkBox_35, 2, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.g5.addWidget(self.pushButton_13, 3, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_16.addWidget(self.label_25)
        self.spinBox_9 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_16.addWidget(self.spinBox_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.checkBox_36 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_36.setObjectName("checkBox_36")
        self.horizontalLayout_17.addWidget(self.checkBox_36)
        self.checkBox_37 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_37.setObjectName("checkBox_37")
        self.horizontalLayout_17.addWidget(self.checkBox_37)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.g5.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.g5, 3, 0, 1, 2)
        self.g6 = QtWidgets.QGridLayout()
        self.g6.setObjectName("g6")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.g6.addWidget(self.lineEdit_23, 0, 1, 1, 1)
        self.checkBox_38 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_38.setObjectName("checkBox_38")
        self.g6.addWidget(self.checkBox_38, 2, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_3)
        self.label_37.setObjectName("label_37")
        self.g6.addWidget(self.label_37, 0, 0, 1, 1)
        self.checkBox_39 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_39.setObjectName("checkBox_39")
        self.g6.addWidget(self.checkBox_39, 2, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_14.setObjectName("pushButton_14")
        self.g6.addWidget(self.pushButton_14, 3, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        self.spinBox_10 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_19.addWidget(self.spinBox_10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.checkBox_40 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_40.setObjectName("checkBox_40")
        self.horizontalLayout_20.addWidget(self.checkBox_40)
        self.checkBox_41 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_41.setObjectName("checkBox_41")
        self.horizontalLayout_20.addWidget(self.checkBox_41)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.g6.addLayout(self.verticalLayout_8, 1, 0, 1, 2)
        self.gridLayout_17.addLayout(self.g6, 3, 2, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(189, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem4, 3, 4, 1, 1)
        self.examples_tabs.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_42 = QtWidgets.QLabel(self.tab)
        self.label_42.setWordWrap(True)
        self.label_42.setObjectName("label_42")
        self.gridLayout_16.addWidget(self.label_42, 0, 0, 1, 1)
        self.vv1 = QtWidgets.QVBoxLayout()
        self.vv1.setObjectName("vv1")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.vv1.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.vv1.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.vv1.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_8.addWidget(self.plainTextEdit)
        self.vv1.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_5.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_5.addWidget(self.checkBox_3)
        self.vv1.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.vv1.addLayout(self.horizontalLayout_6)
        self.gridLayout_16.addLayout(self.vv1, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(425, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem5, 1, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab)
        self.label_41.setWordWrap(True)
        self.label_41.setObjectName("label_41")
        self.gridLayout_16.addWidget(self.label_41, 2, 0, 1, 1)
        self.gg1 = QtWidgets.QGridLayout()
        self.gg1.setObjectName("gg1")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gg1.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gg1.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gg1.addWidget(self.label_6, 2, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gg1.addWidget(self.spinBox_2, 2, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gg1.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gg1.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gg1.addWidget(self.checkBox_5, 4, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gg1.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gg1.addWidget(self.pushButton_2, 5, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setObjectName("label_19")
        self.gg1.addWidget(self.label_19, 3, 0, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gg1.addWidget(self.plainTextEdit_2, 3, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gg1, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(425, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem6, 3, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab)
        self.label_44.setWordWrap(True)
        self.label_44.setObjectName("label_44")
        self.gridLayout_16.addWidget(self.label_44, 1, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab)
        self.label_45.setWordWrap(True)
        self.label_45.setObjectName("label_45")
        self.gridLayout_16.addWidget(self.label_45, 3, 1, 1, 1)
        self.examples_tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_7.addWidget(self.lineEdit_5, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_7.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 2, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_7.addWidget(self.spinBox_3, 2, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_7.addWidget(self.checkBox_6, 3, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_7.addWidget(self.checkBox_7, 3, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setObjectName("frame_3")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_8.setGeometry(QtCore.QRect(9, 87, 70, 18))
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(9, 9, 48, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(9, 61, 19, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(85, 35, 110, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(85, 9, 110, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.spinBox_4 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_4.setGeometry(QtCore.QRect(85, 61, 37, 20))
        self.spinBox_4.setObjectName("spinBox_4")
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_9.setGeometry(QtCore.QRect(85, 87, 100, 18))
        self.checkBox_9.setObjectName("checkBox_9")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(9, 35, 64, 16))
        self.label_12.setObjectName("label_12")
        self.gridLayout_15.addWidget(self.frame_3, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 1, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 2, 0, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout.addWidget(self.spinBox_6, 2, 1, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout.addWidget(self.checkBox_13, 3, 1, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 4, 1, 1, 1)
        self.clickeme__ = QtWidgets.QPushButton(self.groupBox_3)
        self.clickeme__.setObjectName("clickeme__")
        self.gridLayout.addWidget(self.clickeme__, 3, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_29 = QtWidgets.QLabel(self.frame_4)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 0, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_8.addWidget(self.lineEdit_12, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_4)
        self.label_33.setObjectName("label_33")
        self.gridLayout_8.addWidget(self.label_33, 1, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_8.addWidget(self.lineEdit_11, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 2, 0, 1, 1)
        self.spinBox_12 = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout_8.addWidget(self.spinBox_12, 2, 1, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_8.addWidget(self.checkBox_21, 3, 1, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_8.addWidget(self.checkBox_20, 4, 1, 1, 1)
        self.gridLayout_15.addWidget(self.frame_4, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_15.addWidget(self.label_15, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 1, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_15.addWidget(self.label_40, 2, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_15.addWidget(self.label_43, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(399, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem7, 0, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(399, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem8, 3, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(399, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem9, 2, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(399, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem10, 1, 2, 1, 1)
        self.examples_tabs.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.els = QtWidgets.QGroupBox(self.tab_4)
        self.els.setObjectName("els")
        self.sadf = QtWidgets.QGridLayout(self.els)
        self.sadf.setObjectName("sadf")
        self.q1_2 = QtWidgets.QPushButton(self.els)
        self.q1_2.setObjectName("q1_2")
        self.sadf.addWidget(self.q1_2, 1, 0, 1, 2)
        self.radioButton = QtWidgets.QRadioButton(self.els)
        self.radioButton.setObjectName("radioButton")
        self.sadf.addWidget(self.radioButton, 2, 0, 1, 2)
        self.checkBox_42 = QtWidgets.QCheckBox(self.els)
        self.checkBox_42.setObjectName("checkBox_42")
        self.sadf.addWidget(self.checkBox_42, 6, 0, 1, 2)
        self.spinBox_11 = QtWidgets.QSpinBox(self.els)
        self.spinBox_11.setObjectName("spinBox_11")
        self.sadf.addWidget(self.spinBox_11, 7, 0, 1, 2)
        self.horizontalSlider = QtWidgets.QSlider(self.els)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.sadf.addWidget(self.horizontalSlider, 9, 0, 1, 2)
        self.verticalSlider = QtWidgets.QSlider(self.els)
        self.verticalSlider.setMinimumSize(QtCore.QSize(0, 50))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.sadf.addWidget(self.verticalSlider, 10, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.els)
        self.label_13.setObjectName("label_13")
        self.sadf.addWidget(self.label_13, 0, 0, 1, 2)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.els)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.sadf.addWidget(self.dateTimeEdit, 13, 0, 1, 2)
        self.dateEdit = QtWidgets.QDateEdit(self.els)
        self.dateEdit.setObjectName("dateEdit")
        self.sadf.addWidget(self.dateEdit, 12, 0, 1, 2)
        self.timeEdit = QtWidgets.QTimeEdit(self.els)
        self.timeEdit.setObjectName("timeEdit")
        self.sadf.addWidget(self.timeEdit, 11, 0, 1, 2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.els)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.sadf.addWidget(self.doubleSpinBox, 8, 0, 1, 2)
        self.radioButton_2 = QtWidgets.QRadioButton(self.els)
        self.radioButton_2.setObjectName("radioButton_2")
        self.sadf.addWidget(self.radioButton_2, 3, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.els)
        self.radioButton_3.setObjectName("radioButton_3")
        self.sadf.addWidget(self.radioButton_3, 4, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.els)
        self.radioButton_4.setObjectName("radioButton_4")
        self.sadf.addWidget(self.radioButton_4, 5, 0, 1, 1)
        self.gridLayout_3.addWidget(self.els, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(752, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 283, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 1, 0, 1, 1)
        self.examples_tabs.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.examples_tabs.addTab(self.tab_5, "")
        self.gridLayout_2.addWidget(self.examples_tabs, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.examples_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_input_data.setTitle(_translate("MainWindow", "Input data"))
        self.label_17.setText(_translate("MainWindow", "xml file"))
        self.input__file.setText(_translate("MainWindow", "untitled.ui"))
        self.label_39.setText(_translate("MainWindow", "Target object name"))
        self.target_object_name.setText(_translate("MainWindow", "v2"))
        self.file__browse.setText(_translate("MainWindow", "&browse..."))
        self.guitype_qt.setText(_translate("MainWindow", "qt"))
        self.guitype_wx.setText(_translate("MainWindow", "WxWidget"))
        self.guitype_tk.setText(_translate("MainWindow", "Tk"))
        self.guitype_web.setText(_translate("MainWindow", "web"))
        self.compile_.setText(_translate("MainWindow", "co&mpile"))
        self.mouse_clicks_.setText(_translate("MainWindow", "mouse clicks"))
        self.keys_.setText(_translate("MainWindow", "all keys"))
        self.compile_pp.setText(_translate("MainWindow", "compile++"))
        self.clear_psg_output.setText(_translate("MainWindow", "&clear"))
        self.expand_psg_output.setText(_translate("MainWindow", "*  expand  *"))
        self.pass_bad_widgets.setText(_translate("MainWindow", "forget about bad widgets"))
        self.try_run_.setText(_translate("MainWindow", "&try"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p>Vbox. Idea is simple:</p><p>Want to add new row -&gt; make HBox and place elements inside it.</p><p>If u want to create Vbox in Vbox -&gt; make Hbox, place QFrame in it, place VBox in QFrame, Place elements in VBox.</p><p>If u want to create Grid in Vbox -&gt; make Grid, place QFrame in it, place Grid in QFrame, Place elements in Grid.</p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "Age"))
        self.label_23.setText(_translate("MainWindow", "Age"))
        self.checkBox_18.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_19.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.checkBox_10.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_11.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_24.setText(_translate("MainWindow", "Age"))
        self.checkBox_27.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.checkBox_26.setText(_translate("MainWindow", "sex: male"))
        self.lineEdit_18.setText(_translate("MainWindow", "56"))
        self.label_30.setText(_translate("MainWindow", "first name 5"))
        self.pushButton_9.setText(_translate("MainWindow", "submit"))
        self.checkBox_24.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_25.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p>Grid is like Vbox. See examples.</p><p>Elements on multi spans - <span style=\" font-weight:600;\">supported</span></p><p>Grid, Vbox inside grid - <span style=\" font-weight:600;\">supported</span></p></body></html>"))
        self.pushButton_11.setText(_translate("MainWindow", "submit"))
        self.lineEdit_20.setText(_translate("MainWindow", "56"))
        self.checkBox_30.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_31.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_34.setText(_translate("MainWindow", "first name 5"))
        self.checkBox_32.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.checkBox_33.setText(_translate("MainWindow", "sex: male"))
        self.lineEdit_21.setText(_translate("MainWindow", "56"))
        self.label_35.setText(_translate("MainWindow", "first name 5"))
        self.pushButton_12.setText(_translate("MainWindow", "submit"))
        self.pushButton_5.setText(_translate("MainWindow", "submit"))
        self.lineEdit_14.setText(_translate("MainWindow", "56"))
        self.checkBox_14.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_15.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_28.setText(_translate("MainWindow", "first name 5"))
        self.checkBox_17.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.checkBox_16.setText(_translate("MainWindow", "sex: male"))
        self.lineEdit_16.setText(_translate("MainWindow", "56"))
        self.label_32.setText(_translate("MainWindow", "first name 5"))
        self.pushButton_6.setText(_translate("MainWindow", "submit"))
        self.lineEdit_22.setText(_translate("MainWindow", "56"))
        self.checkBox_34.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_36.setText(_translate("MainWindow", "first name 5"))
        self.checkBox_35.setText(_translate("MainWindow", "sex: male"))
        self.pushButton_13.setText(_translate("MainWindow", "submit"))
        self.label_25.setText(_translate("MainWindow", "Age"))
        self.checkBox_36.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_37.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.lineEdit_23.setText(_translate("MainWindow", "56"))
        self.checkBox_38.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_37.setText(_translate("MainWindow", "first name 5"))
        self.checkBox_39.setText(_translate("MainWindow", "sex: male"))
        self.pushButton_14.setText(_translate("MainWindow", "submit"))
        self.label_26.setText(_translate("MainWindow", "Age"))
        self.checkBox_40.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_41.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.examples_tabs.setTabText(self.examples_tabs.indexOf(self.tab_3), _translate("MainWindow", "Page - grid + vbox"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p>Simple vbox</p><p>(without nested containers)</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "first name"))
        self.label.setText(_translate("MainWindow", "Second name"))
        self.label_3.setText(_translate("MainWindow", "Age"))
        self.label_18.setText(_translate("MainWindow", "Desc"))
        self.checkBox_2.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_3.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.pushButton.setText(_translate("MainWindow", "submit"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p>Simple grid</p><p>(without nested containers)</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Second name"))
        self.label_4.setText(_translate("MainWindow", "first name 5"))
        self.label_6.setText(_translate("MainWindow", "Age"))
        self.checkBox_4.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_5.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.lineEdit_3.setText(_translate("MainWindow", "56"))
        self.pushButton_2.setText(_translate("MainWindow", "submit"))
        self.label_19.setText(_translate("MainWindow", "Desc"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p>vv1</p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p>gg1</p></body></html>"))
        self.examples_tabs.setTabText(self.examples_tabs.indexOf(self.tab), _translate("MainWindow", "Page - just simple examples"))
        self.groupBox_2.setTitle(_translate("MainWindow", "groupBox_2"))
        self.label_7.setText(_translate("MainWindow", "first name"))
        self.label_8.setText(_translate("MainWindow", "Second name"))
        self.label_9.setText(_translate("MainWindow", "Age"))
        self.checkBox_6.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_7.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.checkBox_8.setText(_translate("MainWindow", "sex: male"))
        self.label_10.setText(_translate("MainWindow", "first name"))
        self.label_11.setText(_translate("MainWindow", "Age"))
        self.checkBox_9.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_12.setText(_translate("MainWindow", "Second name"))
        self.groupBox_3.setTitle(_translate("MainWindow", "groupBox_3"))
        self.label_14.setText(_translate("MainWindow", "first name"))
        self.label_22.setText(_translate("MainWindow", "Second name"))
        self.label_20.setText(_translate("MainWindow", "Age"))
        self.checkBox_13.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.checkBox_12.setText(_translate("MainWindow", "sex: male"))
        self.clickeme__.setText(_translate("MainWindow", "PushButton"))
        self.label_29.setText(_translate("MainWindow", "first name"))
        self.label_33.setText(_translate("MainWindow", "Second name"))
        self.label_31.setText(_translate("MainWindow", "Age"))
        self.checkBox_21.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.checkBox_20.setText(_translate("MainWindow", "sex: male"))
        self.label_15.setText(_translate("MainWindow", "InValid GroupBox\n"
"reason:\n"
"free layout"))
        self.label_16.setText(_translate("MainWindow", "InValid Frame\n"
"reason:\n"
"free layout"))
        self.label_40.setText(_translate("MainWindow", "Valid GroupBox"))
        self.label_43.setText(_translate("MainWindow", "Valid Frame"))
        self.examples_tabs.setTabText(self.examples_tabs.indexOf(self.tab_2), _translate("MainWindow", "GroupBox, Frame"))
        self.els.setTitle(_translate("MainWindow", "els"))
        self.q1_2.setText(_translate("MainWindow", "q1 button"))
        self.radioButton.setToolTip(_translate("MainWindow", "q1"))
        self.radioButton.setText(_translate("MainWindow", "1"))
        self.checkBox_42.setText(_translate("MainWindow", "CheckBox"))
        self.label_13.setText(_translate("MainWindow", "Кнопки"))
        self.radioButton_2.setToolTip(_translate("MainWindow", "q1"))
        self.radioButton_2.setText(_translate("MainWindow", "2"))
        self.radioButton_3.setToolTip(_translate("MainWindow", "q2"))
        self.radioButton_3.setText(_translate("MainWindow", "11"))
        self.radioButton_4.setToolTip(_translate("MainWindow", "q2"))
        self.radioButton_4.setText(_translate("MainWindow", "12"))
        self.examples_tabs.setTabText(self.examples_tabs.indexOf(self.tab_4), _translate("MainWindow", "Basic elemts"))
        self.examples_tabs.setTabText(self.examples_tabs.indexOf(self.tab_5), _translate("MainWindow", "Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

