# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\python_sandbox\pysimplegui_designer\unittest_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 764)
        MainWindow.setStyleSheet("/*\n"
"border: 1px solid black;\n"
"*/")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(435, 15, 206, 146))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.v1 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.v1.setContentsMargins(0, 0, 0, 0)
        self.v1.setObjectName("v1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.spinBox_5 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_9.addWidget(self.spinBox_5)
        self.v1.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.layoutWidget_2)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.spinBox_7 = QtWidgets.QSpinBox(self.frame_7)
        self.spinBox_7.setObjectName("spinBox_7")
        self.horizontalLayout_13.addWidget(self.spinBox_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBox_18 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_18.setObjectName("checkBox_18")
        self.horizontalLayout_14.addWidget(self.checkBox_18)
        self.checkBox_19 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_19.setObjectName("checkBox_19")
        self.horizontalLayout_14.addWidget(self.checkBox_19)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.v1.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_11.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_11.addWidget(self.checkBox_11)
        self.v1.addLayout(self.horizontalLayout_11)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(825, 365, 256, 156))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.g3 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.g3.setContentsMargins(0, 0, 0, 0)
        self.g3.setObjectName("g3")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.g3.addWidget(self.pushButton_5, 3, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.g3.addWidget(self.lineEdit_14, 0, 1, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_14.setObjectName("checkBox_14")
        self.g3.addWidget(self.checkBox_14, 2, 0, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_15.setObjectName("checkBox_15")
        self.g3.addWidget(self.checkBox_15, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_28.setObjectName("label_28")
        self.g3.addWidget(self.label_28, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_17 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_4.addWidget(self.checkBox_17, 1, 1, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_4.addWidget(self.checkBox_16, 1, 0, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_4.addWidget(self.lineEdit_16, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.g3.addLayout(self.gridLayout_4, 1, 0, 1, 2)
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_6.setGeometry(QtCore.QRect(245, 540, 258, 156))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.g4 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.g4.setContentsMargins(0, 0, 0, 0)
        self.g4.setObjectName("g4")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.g4.addWidget(self.lineEdit_15, 0, 1, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox_21.setObjectName("checkBox_21")
        self.g4.addWidget(self.checkBox_21, 2, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_29.setObjectName("label_29")
        self.g4.addWidget(self.label_29, 0, 0, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox_20.setObjectName("checkBox_20")
        self.g4.addWidget(self.checkBox_20, 2, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.pushButton_8.setObjectName("pushButton_8")
        self.g4.addWidget(self.pushButton_8, 3, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.spinBox_6 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_10.addWidget(self.spinBox_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_12 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_12.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_12.addWidget(self.checkBox_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.g4.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.layoutWidget_8 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_8.setGeometry(QtCore.QRect(435, 170, 210, 151))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.v2 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.v2.setContentsMargins(0, 0, 0, 0)
        self.v2.setObjectName("v2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_15.addWidget(self.label_24)
        self.spinBox_8 = QtWidgets.QSpinBox(self.layoutWidget_8)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_15.addWidget(self.spinBox_8)
        self.v2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_8 = QtWidgets.QFrame(self.layoutWidget_8)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_27 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_6.addWidget(self.checkBox_27, 1, 1, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_6.addWidget(self.checkBox_26, 1, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_6.addWidget(self.lineEdit_18, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_8)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_6.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        self.horizontalLayout_7.addWidget(self.frame_8)
        self.v2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.checkBox_24 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.checkBox_24.setObjectName("checkBox_24")
        self.horizontalLayout_18.addWidget(self.checkBox_24)
        self.checkBox_25 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.checkBox_25.setObjectName("checkBox_25")
        self.horizontalLayout_18.addWidget(self.checkBox_25)
        self.v2.addLayout(self.horizontalLayout_18)
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(245, 365, 256, 156))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.g1 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.g1.setContentsMargins(0, 0, 0, 0)
        self.g1.setObjectName("g1")
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pushButton_7.setObjectName("pushButton_7")
        self.g1.addWidget(self.pushButton_7, 3, 1, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.g1.addWidget(self.lineEdit_17, 0, 1, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkBox_22.setObjectName("checkBox_22")
        self.g1.addWidget(self.checkBox_22, 2, 0, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkBox_23.setObjectName("checkBox_23")
        self.g1.addWidget(self.checkBox_23, 2, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_31.setObjectName("label_31")
        self.g1.addWidget(self.label_31, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox_28 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout_8.addWidget(self.checkBox_28, 1, 1, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout_8.addWidget(self.checkBox_29, 1, 0, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_8.addWidget(self.lineEdit_19, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_8.addWidget(self.label_33, 0, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_8.addWidget(self.pushButton_10, 2, 1, 1, 1)
        self.g1.addLayout(self.gridLayout_8, 1, 1, 1, 1)
        self.layoutWidget_7 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_7.setGeometry(QtCore.QRect(520, 365, 286, 156))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.g2 = QtWidgets.QGridLayout(self.layoutWidget_7)
        self.g2.setContentsMargins(0, 0, 0, 0)
        self.g2.setObjectName("g2")
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget_7)
        self.pushButton_11.setObjectName("pushButton_11")
        self.g2.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.g2.addWidget(self.lineEdit_20, 0, 1, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_30.setObjectName("checkBox_30")
        self.g2.addWidget(self.checkBox_30, 2, 0, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_31.setObjectName("checkBox_31")
        self.g2.addWidget(self.checkBox_31, 2, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_34.setObjectName("label_34")
        self.g2.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.checkBox_32 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_10.addWidget(self.checkBox_32, 1, 1, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout_10.addWidget(self.checkBox_33, 1, 0, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_10.addWidget(self.lineEdit_21, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_35.setObjectName("label_35")
        self.gridLayout_10.addWidget(self.label_35, 0, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget_7)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_10.addWidget(self.pushButton_12, 2, 1, 1, 1)
        self.g2.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.layoutWidget_9 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_9.setGeometry(QtCore.QRect(520, 540, 288, 156))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.g5 = QtWidgets.QGridLayout(self.layoutWidget_9)
        self.g5.setContentsMargins(0, 0, 0, 0)
        self.g5.setObjectName("g5")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.g5.addWidget(self.lineEdit_22, 0, 1, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.checkBox_34.setObjectName("checkBox_34")
        self.g5.addWidget(self.checkBox_34, 2, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_36.setObjectName("label_36")
        self.g5.addWidget(self.label_36, 0, 0, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.checkBox_35.setObjectName("checkBox_35")
        self.g5.addWidget(self.checkBox_35, 2, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget_9)
        self.pushButton_13.setObjectName("pushButton_13")
        self.g5.addWidget(self.pushButton_13, 3, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_16.addWidget(self.label_25)
        self.spinBox_9 = QtWidgets.QSpinBox(self.layoutWidget_9)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_16.addWidget(self.spinBox_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.checkBox_36 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.checkBox_36.setObjectName("checkBox_36")
        self.horizontalLayout_17.addWidget(self.checkBox_36)
        self.checkBox_37 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.checkBox_37.setObjectName("checkBox_37")
        self.horizontalLayout_17.addWidget(self.checkBox_37)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.g5.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.layoutWidget_10 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_10.setGeometry(QtCore.QRect(825, 545, 256, 156))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.g6 = QtWidgets.QGridLayout(self.layoutWidget_10)
        self.g6.setContentsMargins(0, 0, 0, 0)
        self.g6.setObjectName("g6")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget_10)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.g6.addWidget(self.lineEdit_23, 0, 1, 1, 1)
        self.checkBox_38 = QtWidgets.QCheckBox(self.layoutWidget_10)
        self.checkBox_38.setObjectName("checkBox_38")
        self.g6.addWidget(self.checkBox_38, 2, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_37.setObjectName("label_37")
        self.g6.addWidget(self.label_37, 0, 0, 1, 1)
        self.checkBox_39 = QtWidgets.QCheckBox(self.layoutWidget_10)
        self.checkBox_39.setObjectName("checkBox_39")
        self.g6.addWidget(self.checkBox_39, 2, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget_10)
        self.pushButton_14.setObjectName("pushButton_14")
        self.g6.addWidget(self.pushButton_14, 3, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        self.spinBox_10 = QtWidgets.QSpinBox(self.layoutWidget_10)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_19.addWidget(self.spinBox_10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.checkBox_40 = QtWidgets.QCheckBox(self.layoutWidget_10)
        self.checkBox_40.setObjectName("checkBox_40")
        self.horizontalLayout_20.addWidget(self.checkBox_40)
        self.checkBox_41 = QtWidgets.QCheckBox(self.layoutWidget_10)
        self.checkBox_41.setObjectName("checkBox_41")
        self.horizontalLayout_20.addWidget(self.checkBox_41)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.g6.addLayout(self.verticalLayout_8, 1, 0, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(25, 20, 331, 151))
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        self.label_38.setGeometry(QtCore.QRect(15, 365, 201, 41))
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(35, 70, 256, 206))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_8.addWidget(self.plainTextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_5.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_5.addWidget(self.checkBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 365, 256, 194))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 2, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 4, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 3, 0, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.layoutWidget_3)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout.addWidget(self.plainTextEdit_2, 3, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab)
        self.label_41.setGeometry(QtCore.QRect(55, 320, 201, 41))
        self.label_41.setWordWrap(True)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab)
        self.label_42.setGeometry(QtCore.QRect(65, 25, 201, 41))
        self.label_42.setWordWrap(True)
        self.label_42.setObjectName("label_42")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 30, 281, 146))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_6.setGeometry(QtCore.QRect(45, 95, 68, 16))
        self.checkBox_6.setObjectName("checkBox_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(45, 23, 56, 16))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(45, 71, 27, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(123, 47, 108, 18))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(123, 23, 108, 18))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3.setGeometry(QtCore.QRect(123, 71, 35, 18))
        self.spinBox_3.setObjectName("spinBox_3")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_7.setGeometry(QtCore.QRect(123, 95, 98, 16))
        self.checkBox_7.setObjectName("checkBox_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(45, 47, 72, 16))
        self.label_8.setObjectName("label_8")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(15, 200, 281, 146))
        self.frame_3.setObjectName("frame_3")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_8.setGeometry(QtCore.QRect(45, 95, 68, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(45, 23, 56, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(45, 71, 27, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(123, 47, 108, 18))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(123, 23, 108, 18))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.spinBox_4 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_4.setGeometry(QtCore.QRect(123, 71, 35, 18))
        self.spinBox_4.setObjectName("spinBox_4")
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_9.setGeometry(QtCore.QRect(123, 95, 98, 16))
        self.checkBox_9.setObjectName("checkBox_9")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(45, 47, 72, 16))
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(330, 235, 86, 16))
        self.label_16.setObjectName("label_16")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(315, 65, 86, 16))
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_21.setText(_translate("MainWindow", "Age"))
        self.label_23.setText(_translate("MainWindow", "Age"))
        self.checkBox_18.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_19.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.checkBox_10.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_11.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.pushButton_5.setText(_translate("MainWindow", "submit"))
        self.lineEdit_14.setText(_translate("MainWindow", "56"))
        self.checkBox_14.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_15.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_28.setText(_translate("MainWindow", "first name 5"))
        self.checkBox_17.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.checkBox_16.setText(_translate("MainWindow", "sex: male"))
        self.lineEdit_16.setText(_translate("MainWindow", "56"))
        self.label_32.setText(_translate("MainWindow", "first name 5"))
        self.pushButton_6.setText(_translate("MainWindow", "submit"))
        self.lineEdit_15.setText(_translate("MainWindow", "56"))
        self.checkBox_21.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_29.setText(_translate("MainWindow", "first name 5"))
        self.checkBox_20.setText(_translate("MainWindow", "sex: male"))
        self.pushButton_8.setText(_translate("MainWindow", "submit"))
        self.label_22.setText(_translate("MainWindow", "Age"))
        self.checkBox_12.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_13.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_24.setText(_translate("MainWindow", "Age"))
        self.checkBox_27.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.checkBox_26.setText(_translate("MainWindow", "sex: male"))
        self.lineEdit_18.setText(_translate("MainWindow", "56"))
        self.label_30.setText(_translate("MainWindow", "first name 5"))
        self.pushButton_9.setText(_translate("MainWindow", "submit"))
        self.checkBox_24.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_25.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.pushButton_7.setText(_translate("MainWindow", "submit"))
        self.lineEdit_17.setText(_translate("MainWindow", "56"))
        self.checkBox_22.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_23.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_31.setText(_translate("MainWindow", "first name 5"))
        self.checkBox_28.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.checkBox_29.setText(_translate("MainWindow", "sex: male"))
        self.lineEdit_19.setText(_translate("MainWindow", "56"))
        self.label_33.setText(_translate("MainWindow", "first name 5"))
        self.pushButton_10.setText(_translate("MainWindow", "submit"))
        self.pushButton_11.setText(_translate("MainWindow", "submit"))
        self.lineEdit_20.setText(_translate("MainWindow", "56"))
        self.checkBox_30.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_31.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_34.setText(_translate("MainWindow", "first name 5"))
        self.checkBox_32.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.checkBox_33.setText(_translate("MainWindow", "sex: male"))
        self.lineEdit_21.setText(_translate("MainWindow", "56"))
        self.label_35.setText(_translate("MainWindow", "first name 5"))
        self.pushButton_12.setText(_translate("MainWindow", "submit"))
        self.lineEdit_22.setText(_translate("MainWindow", "56"))
        self.checkBox_34.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_36.setText(_translate("MainWindow", "first name 5"))
        self.checkBox_35.setText(_translate("MainWindow", "sex: male"))
        self.pushButton_13.setText(_translate("MainWindow", "submit"))
        self.label_25.setText(_translate("MainWindow", "Age"))
        self.checkBox_36.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_37.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.lineEdit_23.setText(_translate("MainWindow", "56"))
        self.checkBox_38.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_37.setText(_translate("MainWindow", "first name 5"))
        self.checkBox_39.setText(_translate("MainWindow", "sex: male"))
        self.pushButton_14.setText(_translate("MainWindow", "submit"))
        self.label_26.setText(_translate("MainWindow", "Age"))
        self.checkBox_40.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_41.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p>Vbox</p><p>Idea is simple:</p><p>Want to add new row -&gt; make HBox and place elements inside it.</p><p>If u want to create Vbox in Vbox -&gt; make Hbox, place QFrame in it, place VBox in QFrame, Place elements in VBox.</p><p>If u want to create Grid in Vbox -&gt; make Grid, place QFrame in it, place Grid in QFrame, Place elements in Grid.</p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p>Grid is like Vbox. See examples.</p><p>Elements on multi spans - <span style=\" font-weight:600;\">supported</span></p><p>Grid, Vbox inside grid - <span style=\" font-weight:600;\">supported</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page - grid + vbox"))
        self.label_2.setText(_translate("MainWindow", "first name"))
        self.label.setText(_translate("MainWindow", "Second name"))
        self.label_3.setText(_translate("MainWindow", "Age"))
        self.label_18.setText(_translate("MainWindow", "Desc"))
        self.checkBox_2.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_3.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.pushButton.setText(_translate("MainWindow", "submit"))
        self.label_5.setText(_translate("MainWindow", "Second name"))
        self.label_4.setText(_translate("MainWindow", "first name 5"))
        self.label_6.setText(_translate("MainWindow", "Age"))
        self.checkBox_4.setText(_translate("MainWindow", "sex: male"))
        self.checkBox_5.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.lineEdit_3.setText(_translate("MainWindow", "56"))
        self.pushButton_2.setText(_translate("MainWindow", "submit"))
        self.label_19.setText(_translate("MainWindow", "Desc"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p>Simple grid</p><p>(without nested containers)</p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p>Simple vbox</p><p>(without nested containers)</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page - just simple examples"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.checkBox_6.setText(_translate("MainWindow", "sex: male"))
        self.label_7.setText(_translate("MainWindow", "first name"))
        self.label_9.setText(_translate("MainWindow", "Age"))
        self.checkBox_7.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_8.setText(_translate("MainWindow", "Second name"))
        self.checkBox_8.setText(_translate("MainWindow", "sex: male"))
        self.label_10.setText(_translate("MainWindow", "first name"))
        self.label_11.setText(_translate("MainWindow", "Age"))
        self.checkBox_9.setText(_translate("MainWindow", "Is Enterprenuer"))
        self.label_12.setText(_translate("MainWindow", "Second name"))
        self.label_16.setText(_translate("MainWindow", "Frame"))
        self.label_15.setText(_translate("MainWindow", "GroupBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

